### ISSUE TITLE
不支持指定属性作为ZK 的 id吗？

### ISSUE THREAD

**Issue by wwjCMP** [terrychenzw/obsidian-zettelkasten-navigation#1]
这样的话，无法和现有的笔记兼容使用。

**Comment by terrychenzw** [comment]
当前版本不支持，将来或者会做，技术上可行。

**Comment by Ravenclawer** [comment]
请问能否支持全库中任意带ZK id的笔记标题，目前是指定了文件夹的，或者说能否指定多个文件夹，这样可能更灵活一些

**Comment by wwjCMP** [comment]
> 请问能否支持全库中任意带ZK id的笔记标题，目前是指定了文件夹的，或者说能否指定多个文件夹，这样可能更灵活一些

确实，如果要提供通用性还要结合这个。不过现在直接将主要文件目录设为根目录行不行？

**Comment by Ravenclawer** [comment]
我还在摸索中，我之前用的breadcrumbs插件，里面有一个johnny decimal notes的功能。对于10 work 、10.1 software development、10.2 DJ mixing、10.3 uber drive 这样的笔记，可以自动识别 10.1、10.2、10.3 这样的前缀，还可以自定义分隔符为点好或者横杠号，将10 work 识别为10.1 software development、10.2 DJ mixing、10.3 uber drive的父笔记，将10.1 software development、10.2 DJ mixing、10.3 uber drive 识别为兄弟笔记。这样既能有编码的优势，又可以满足文件命名的需要，照顾到了一般使用者。毕竟所有笔记全是由编码命名还是太硬核了。

**Comment by terrychenzw** [comment]
> 请问能否支持全库中任意带ZK id的笔记标题，目前是指定了文件夹的，或者说能否指定多个文件夹，这样可能更灵活一些

将来或者会增加按标签来定位ZK卡片。全库检索带 ZK id的笔记文件——这个检索效率太低。 使用文件夹、标签或它们的组合来检索，相对通用一些

**Comment by terrychenzw** [comment]
> 我还在摸索中，我之前用的breadcrumbs插件，里面有一个johnny decimal notes的功能。对于10 work 、10.1 software development、10.2 DJ mixing、10.3 uber drive 这样的笔记，可以自动识别 10.1、10.2、10.3 这样的前缀，还可以自定义分隔符为点好或者横杠号，将10 work 识别为10.1 software development、10.2 DJ mixing、10.3 uber drive的父笔记，将10.1 software development、10.2 DJ mixing、10.3 uber drive 识别为兄弟笔记。这样既能有编码的优势，又可以满足文件命名的需要，照顾到了一般使用者。毕竟所有笔记全是由编码命名还是太硬核了。

将来的版本会考虑扩展以下两种命名规则：
A: 文字标题作为文件名，ID保存在用户指定的frontmatter字段。ID可以留空——则节点不生成在树中，方便给一些未定位的笔记
B: ID+文字标题作为文件名，使用正则来截取分隔符（比如空格）的前面部分作为ID, 后面部分为标题

**Comment by Ravenclawer** [comment]
好的呢，感谢您的回复，目前还是没能理解为什么需要额外的index note folder的原因，我理解就是对于标题中带有johnny decimal的笔记，在侧边栏将该数字的父笔记
、子笔记、兄弟笔记全链路展示出来，相当于在双向链接、文件夹、标签的基础上，多了一种文件的组织形式。

目前的系统理解起来，像是鼓励大家记录atomic notes，在这个文件夹中笔记都是一张张卡片。而在index note中通过链接将卡片以链接的形式组织起来。

但看示例库中，index note是每个笔记中只有一个卡片。好像这个文件夹只起到了指示纯数字标题的笔记的内容的作用。这样看起来就有一些冗余了

可以将johnny decimal + title作为标题，这样就不用特定指定一个文件夹了，卡片本身就可以有zettelkasten-navigation的功能。

也可能是我没有理解到位，总之，感谢开发这么有潜力的插件，这个插件的功能是breadcrumbs插件和excalibrain插件无法提供的，breadcrumbs插件的johnny decimal功能只能看到直属的父节点或兄弟节点或子节点，很难可视化笔记之间复杂的非链接型链路关系。

**Comment by terrychenzw** [comment]
> 好的呢，感谢您的回复，目前还是没能理解为什么需要额外的index note folder的原因，我理解就是对于标题中带有johnny decimal的笔记，在侧边栏将该数字的父笔记 、子笔记、兄弟笔记全链路展示出来，相当于在双向链接、文件夹、标签的基础上，多了一种文件的组织形式。
> 
> 目前的系统理解起来，像是鼓励大家记录atomic notes，在这个文件夹中笔记都是一张张卡片。而在index note中通过链接将卡片以链接的形式组织起来。
> 
> 但看示例库中，index note是每个笔记中只有一个卡片。好像这个文件夹只起到了指示纯数字标题的笔记的内容的作用。这样看起来就有一些冗余了
> 
> 可以将johnny decimal + title作为标题，这样就不用特定指定一个文件夹了，卡片本身就可以有zettelkasten-navigation的功能。
> 
> 也可能是我没有理解到位，总之，感谢开发这么有潜力的插件，这个插件的功能是breadcrumbs插件和excalibrain插件无法提供的，breadcrumbs插件的johnny decimal功能只能看到直属的父节点或兄弟节点或子节点，很难可视化笔记之间复杂的非链接型链路关系。

我之前有做了一个系列视频来解释我的zettelkasten实践。关于index的理解可以看：[检索想法](https://www.bilibili.com/video/BV14v421r7Sy/?spm_id_from=333.788&vd_source=0fc7cc117b82a618be4257462f96f0aa)

**Comment by Ravenclawer** [comment]
好的呢，个人建议以“G203-1A 笔记方法”作为笔记的标题，可能比以“G203-1A”作为笔记标题，之后再到另外一个文件夹中新建一个标题为“笔记方法“的笔记，再连接到G203-1A更加简洁高效一些，本身给出的信息的是一样的，而后者更加繁琐。

**Comment by wwjCMP** [comment]
> > 请问能否支持全库中任意带ZK id的笔记标题，目前是指定了文件夹的，或者说能否指定多个文件夹，这样可能更灵活一些
> 
> 将来或者会增加按标签来定位ZK卡片。全库检索带 ZK id的笔记文件——这个检索效率太低。 使用文件夹、标签或它们的组合来检索，相对通用一些

我觉得使用特定的标签表明它是ZK卡片就行，比如 #ZK 。标签本身就是一种更加灵活的文件夹。

**Comment by terrychenzw** [comment]
> > > 请问能否支持全库中任意带ZK id的笔记标题，目前是指定了文件夹的，或者说能否指定多个文件夹，这样可能更灵活一些
> > 
> > 
> > 将来或者会增加按标签来定位ZK卡片。全库检索带 ZK id的笔记文件——这个检索效率太低。 使用文件夹、标签或它们的组合来检索，相对通用一些
> 
> 我觉得使用特定的标签表明它是ZK卡片就行，比如 #ZK 。标签本身就是一种更加灵活的文件夹。

index还有一个作用，就是2次组织。它允许包含多个分支的。

场景：当你有了很多不同树/分支之后，有一天，你偶然发现A树下的A1分支，和B树下的B2分支，它们结合起来，对你来说能产生一些新的思考。这时，你就可以建一个新的关键词，包含这个2个分支。你也可以在这个新的关键词文件里，加一些简单的描述，来说明这2个分支的关系，以记录和促进你新的思考。将来你要做输出的时候，根据输出的主题，通过关键词，就马上可以找到最相关的分支。

当前我的关键词索引大部分只有一个单一入口链接，是因为我的笔记数量（分支）还没有到一定的量级。我觉得，等到分支/树多了之后，新想法（惊喜制造）就可以通过分支组合来产生——这个是我理解的自下而上发展写作主题的逻辑。

**Comment by Ravenclawer** [comment]
懂了，这样的话其实可以不用拘泥于两个文件夹组织结构，对于文献库中有johnny decimal的每个文件，如10 xxx、10.1 xxx、10.2 xxx，都可以通过”10“、”10.1“、”10.2“这样的前缀生成的树状结构。
而如果有一个笔记没有前缀，名称为xxx，但笔记内部有指向10.1 xxx以及20.3 xxx的双链，这样的话这个名为xxx的笔记可以被归入到10.1 xxx和20.3 xxx 所在的树状结构中。
这样的话就将双链和树状结构结合起来了。

**Comment by Ravenclawer** [comment]
懂了，这样的话其实可以不用拘泥于两个文件夹组织结构，对于文献库中有johnny decimal的每个文件，如10 xxx、10.1 xxx、10.2 xxx，都可以通过”10“、”10.1“、”10.2“这样的前缀生成的树状结构。
而如果有一个笔记没有前缀，名称为xxx，但笔记内部有指向10.1 xxx以及20.3 xxx的双链，这样的话这个名为xxx的笔记可以被归入到10.1 xxx和20.3 xxx 所在的树状结构中。
这样的话就将双链和树状结构结合起来了。

**Comment by wwjCMP** [comment]
> > > > 请问能否支持全库中任意带ZK id的笔记标题，目前是指定了文件夹的，或者说能否指定多个文件夹，这样可能更灵活一些
> > > 
> > > 
> > > 将来或者会增加按标签来定位ZK卡片。全库检索带 ZK id的笔记文件——这个检索效率太低。 使用文件夹、标签或它们的组合来检索，相对通用一些
> > 
> > 
> > 我觉得使用特定的标签表明它是ZK卡片就行，比如 #ZK 。标签本身就是一种更加灵活的文件夹。
> 
> index还有一个作用，就是2次组织。它允许包含多个分支的。
> 
> 场景：当你有了很多不同树/分支之后，有一天，你偶然发现A树下的A1分支，和B树下的B2分支，它们结合起来，对你来说能产生一些新的思考。这时，你就可以建一个新的关键词，包含这个2个分支。你也可以在这个新的关键词文件里，加一些简单的描述，来说明这2个分支的关系，以记录和促进你新的思考。将来你要做输出的时候，根据输出的主题，通过关键词，就马上可以找到最相关的分支。
> 
> 当前我的关键词索引大部分只有一个单一入口链接，是因为我的笔记数量（分支）还没有到一定的量级。我觉得，等到分支/树多了之后，新想法（惊喜制造）就可以通过分支组合来产生——这个是我理解的自下而上发展写作主题的逻辑。

index 我觉得当前的做法可以了，单独指定一个文件夹存放index文件，相对于树的入口。我本身在使用ob也会专门设置一个index系统

**Comment by terrychenzw** [comment]
转移到 [issue 4](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/issues/4)

**Comment by terrychenzw** [comment]
转移到 [issue 4](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/issues/4)

**Comment by terrychenzw** [comment]
> 好的呢，个人建议以“G203-1A 笔记方法”作为笔记的标题，可能比以“G203-1A”作为笔记标题，之后再到另外一个文件夹中新建一个标题为“笔记方法“的笔记，再连接到G203-1A更加简洁高效一些，本身给出的信息的是一样的，而后者更加繁琐。

经过慎重考虑，下个版本将增加直接使用主笔记来生成分支。也就是说，即使不使用单独的关键词文件，也能使用本插件。

主要考虑到：
1. 对于zettelkasten 初学者来说，笔记数量没有达到一定量级，不容易理解关键词的作用和意义
2. 减低插件的使用门槛，允许用户按自己对 zettelkasten 的理解程度和所处阶段，来决定什么时候启用关键词索引

大致效果：

https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/114856910/03d79afa-3f20-4fb2-aabc-0558967795b0

**Comment by Ravenclawer** [comment]
这样对于初学者用起来更加直观一些，对于有多个在不同分枝外链的主笔记，新的版本处理起来会不会有困难呢，毕竟之前是在单独的一个文件夹内创建这种链接到多个主笔记的笔记，而现在只有主笔记。比如在一个文件夹内创建“笔记方法”这个笔记，连接到主笔记文件夹内的“G203-1A“和”G303-2B“ 两个主笔记，这样在这个”笔记方法“的zettel页面中就会有两个树、如果是”G203-1A：笔记方法“ 链接到”G303-2B 输入与表达“ ，在 ”G203-1A：笔记方法“ 中是不是也可以看到”G303-2B 输入与表达“的链接树呢

**Comment by terrychenzw** [comment]
> 这样对于初学者用起来更加直观一些，对于有多个在不同分枝外链的主笔记，新的版本处理起来会不会有困难呢，毕竟之前是在单独的一个文件夹内创建这种链接到多个主笔记的笔记，而现在只有主笔记。比如在一个文件夹内创建“笔记方法”这个笔记，连接到主笔记文件夹内的“G203-1A“和”G303-2B“ 两个主笔记，这样在这个”笔记方法“的zettel页面中就会有两个树、如果是”G203-1A：笔记方法“ 链接到”G303-2B 输入与表达“ ，在 ”G203-1A：笔记方法“ 中是不是也可以看到”G303-2B 输入与表达“的链接树呢。

不确定我是否有理解你的意思。

如果一个主笔记（A）被多个主笔记引用，那么这些主笔记就都是A的入链（反向链接）。可以在右侧的局部关系视图中的入链图谱里查到A的所有入链。然后根据需要来选择是否打开A的某一个入链笔记。一旦打开其中一个，在邻近图谱里就会展示这个笔记所在分支的父节点，手足节点和子节点。A有多少个入链主笔记，就代表有多少个入链分支。

当主笔记到一定量级，一定会有使用关键词索引的需求。这个时候可以无缝启用关键词索引，原先的主笔记不需要任何调整。
