### ISSUE TITLE
Index:“********"has no valid main note outlinks

### ISSUE THREAD

**Issue by 1067237855** [terrychenzw/obsidian-zettelkasten-navigation#10]
一直显示Index:“********"has no valid main note outlinks
![image](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/104330036/79ce56be-1c1a-4119-b561-b6250c99cbd3)

![image](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/104330036/540fd1a5-4452-4a7c-b81b-2c5cba8503dc)

试了很多遍，还是不会用这个插件😂，希望大佬能出个详细教程
index文件夹是怎么设置的？B站里没有介绍

**Comment by terrychenzw** [comment]
在index文件夹下，新建一个文件“测试关键词”，然后在这个文件里面，包含一个主笔记的链接，如 [[1a 测试]]。

按你的截图，插件设置页如下：
![image](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/114856910/692ca1ab-a724-4a73-9d0e-375bc97f2ca3)


等正式上架到OB三方插件市场后，会出视频或完善README。

**Comment by terrychenzw** [comment]
[中文介绍](zettelkasten-navigation]( https://pkmer.cn/show/20240506222202）
