### ISSUE TITLE
[Feature Request]：类似思维导图的子卡片和同级卡片创建按钮

### ISSUE THREAD

**Issue by xyy-1997** [terrychenzw/obsidian-zettelkasten-navigation#11]
首先感谢作者大大开发这个插件，它对知识体系的梳理非常有效，但是不知道是不是我自己的原因，目前我没有发现比较方便的新建卡片的方式。目前我新建卡片的方式是：
- Quickadd命令，调用一个模板文件
- 输入标题
- 输入id

这样会有一个缺点，就是每次我都要记住父节点的id，这样不是很方便。有没有可能添加类似思维导图的添加新节点的功能：
![image](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/56293318/6ac0bf09-927a-419a-be2d-405e2ed52fe5)
- 按钮1：新建子节点
    - 如果父节点后没有，则创建TP319-1-1-1-1
    - 如果父节点后有TP319-1-1-1-n，则创建TP319-1-1-1-(n+1)
- 按钮2：新建同级节点
    - 如果没有同级节点，点击创建TP319-1-1-1a
    - 如果有同级节点TP319-1-1-1a，则创建TP319-1-1-1b，以此类推

这样我就只用输入标题就可以了，无需记住之前的节点id。

**Comment by terrychenzw** [comment]
自动生成新节点的ID这个有点难。要做这个功能主要有这些需要考虑的点：
1. 每个人的ID规则不同，有使用层级分隔符的和也有不用分隔符的，规则很难做到统一
2. ID字段保存位置不同，有用文件名的，有用属性字段的，还有用文件名前缀的

另外：
1. 在树状图节点上加太多的小图标会到来混乱
2. 不用图标的话，我更偏向于快捷键创建的方式是：选中一个节点，按 tab/或其他键来创建

虽然树状图很容易就联想到思维导图，但这个插件的核心本质是图谱，主要实现笔记关系的呈现，所以暂时不考虑创建/修改/删除这些操作。

或者可以考虑在节点增加复制ID的功能，比如双击节点，ctr/alt/shift + 单击节点等方式来复制ID.

**Comment by xyy-1997** [comment]
> 自动生成新节点的ID这个有点难。要做这个功能主要有这些需要考虑的点：
> 
> 1. 每个人的ID规则不同，有使用层级分隔符的和也有不用分隔符的，规则很难做到统一
> 2. ID字段保存位置不同，有用文件名的，有用属性字段的，还有用文件名前缀的
> 
> 另外：
> 
> 1. 在树状图节点上加太多的小图标会到来混乱
> 2. 不用图标的话，我更偏向于快捷键创建的方式是：选中一个节点，按 tab/或其他键来创建
> 
> 虽然树状图很容易就联想到思维导图，但这个插件的核心本质是图谱，主要实现笔记关系的呈现，所以暂时不考虑创建/修改/删除这些操作。
> 
> 或者可以考虑在节点增加复制ID的功能，比如双击节点，ctr/alt/shift + 单击节点等方式来复制ID.

确实有道理，那我觉得复制ID的功能可能是比较现实的。

**Comment by terrychenzw** [comment]
[0.0.35](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/releases/tag/0.0.35)已支持 Ctrl+click 来复制ID.

> 如果您觉得这个插件有用，并希望支持其开发，您可以通过以下方式赞助我：微信，支付宝。感谢您的任何支持！
>
> [打赏作者](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/issues/3#issuecomment-2106543059)

**Comment by terrychenzw** [comment]
下个版本将增加右键菜单，可添加自定义命令，[功能效果](https://www.bilibili.com/video/BV1pzxjerENq/?spm_id_from=333.1365.list.card_archive.click)
