### ISSUE TITLE
[FR]: 添加自动聚焦到当前节点

### ISSUE THREAD

**Issue by Leiyi548** [terrychenzw/obsidian-zettelkasten-navigation#14]
默认打开是这个样子：
![5039c687b7de9eed85c02149632cf05](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/76139422/621d0d2c-65be-4da3-8e9c-b523b459d952)

我想这个样子：

**Comment by Leiyi548** [comment]
![c2bff57c91b4d1e821493a74c0103b0](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/76139422/ce6ae690-71d0-4033-854a-f87a0617aea0)

**Comment by terrychenzw** [comment]
起点选择分支入口是否可以了？

**Comment by Leiyi548** [comment]
> 起点选择分支入口是否可以了？

就是起点选择，我的意思是聚焦到选择的那个分支

**Comment by terrychenzw** [comment]
当前是支持手动按住左键平移，和鼠标滚轮缩放的。自动缩放就需要一些平移和缩放值的计算，另外还要考虑缩放比例式多少。每个人的喜好都不同，就要考虑做配置。还不然手工平移和缩放来得简单和易用

**Comment by terrychenzw** [comment]
保持手工拖动和滚轮缩放的操作方式，暂不考虑自动聚焦。
