### ISSUE TITLE
[FR] 取消下划线

### ISSUE THREAD

**Issue by wwjCMP** [terrychenzw/obsidian-zettelkasten-navigation#16]
![image](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/32979859/6fe4e100-7bd0-403c-9759-9ed455367590)

文字的下划线是不是没什么必要？如果编号使用_，还会受到干扰

**Comment by terrychenzw** [comment]
这个可以通过自定义css来控制链接的样式。

譬如，Minimal主题就隐藏链接的下划线，只有当鼠标指向链接的时候，才显示下划线。
