### ISSUE TITLE
[FR] 开启和关闭递归折叠与递归展开

### ISSUE THREAD

**Issue by wwjCMP** [terrychenzw/obsidian-zettelkasten-navigation#18]
就是字面意思。这个相关的可以参考obsidian 脑图插件
![image](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/32979859/4bfd6816-aae9-4f22-abdf-e249009caa37)

**Comment by terrychenzw** [comment]
对这个插件不熟悉，请详细描述需求。

**Comment by wwjCMP** [comment]
> 对这个插件不熟悉，请详细描述需求。

就是递归展开，和递归折叠。将操作节点和所属子节点一起操作

**Comment by wwjCMP** [comment]
就是折叠当前节点的时候，它所有的子节点，以及子节点的子节点....，都进行折叠

**Comment by terrychenzw** [comment]
你说的是这样的折叠效果吧？
![markmap](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/114856910/894cd54e-1005-40e4-996f-4bea44c97a20)

要实现这种效果，画树状图使用的技术就要从 Mermaid 转到 Markmap.

**Comment by wwjCMP** [comment]
不是动画效果，还是折叠逻辑方面的

**Comment by terrychenzw** [comment]
> 不是动画效果，还是折叠逻辑方面的

真的没有理解你的意思，可以的话请举例详细描述。

**Comment by wwjCMP** [comment]
可以参考一下递归检索，比如在linux，可以只检索当前目录下的文件，也可以递归检索又有子目录

**Comment by cygroup** [comment]
@wwjCMP 的意思应该是，展开一个节点时，将其下的所有子节点，所有子节点下的孙节点......全部一起自动展开，而不是需要一层一层地分别手动去点击展开，折叠也类似。

**Comment by terrychenzw** [comment]
> @wwjCMP 的意思应该是，展开一个节点时，将其下的所有子节点，所有子节点下的孙节点......全部一起自动展开，而不是需要一层一层地分别手动去点击展开，折叠也类似。

如果是这个意思的话，当前是，如果一个节点点击折叠，就会记录。只有在再次点击该节点，或切换关键词才会清空该节点的折叠记录。

应该2种需求都是存在的。或者可以考虑通过单击和双击来区分：
单击：不清空下层节点有过的折叠记录
双击：清空所有下层节点有过的折叠记录

**Comment by terrychenzw** [comment]
> 使用Ctrl 键来区分：
> click：不清空下层节点有过的折叠记录
> ctrl + click: 清空下层节点有过的折叠记录

版本 0.0.50 已完成
