### ISSUE TITLE
[FR] 出链入链的显示方式可以参考excalibrain

### ISSUE THREAD

**Issue by wwjCMP** [terrychenzw/obsidian-zettelkasten-navigation#19]
增加纵向空间，减少横向空间。这样在出链数和入链数较多的时候更好地显示

**Comment by wwjCMP** [comment]
顺便把出链和入链界面统一起来

**Comment by terrychenzw** [comment]
> 增加纵向空间，减少横向空间。这样在出链数和入链数较多的时候更好地显示

这个没有理解，可以的话麻烦截图说明

**Comment by terrychenzw** [comment]
> 顺便把出链和入链界面统一起来

是指出链和入链合在一个视图理解吧？

之所以分开，主要是考虑每个出链或入链，都是不同的思路，全部放在一个视图里会混乱（这个是我对核心插件关系图谱的局部视图的看法）。

合在一起也可以考虑，因为不同的人的应用场景是不同的。实现的话就偏向增加一个出入链视图。按自己的喜好来选择打开哪个。
