### ISSUE TITLE
笔记修改后，再回到关键词分支视图，会失效

### ISSUE THREAD

**Issue by cygroup** [terrychenzw/obsidian-zettelkasten-navigation#20]
当我通过关键词分支视图，打开一个笔记，然后修改笔记内容后，再回到关键词分支视图，此时分支视图会变成无效状态（参见附件）
![008](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/96104161/ac3f1430-6b47-4102-be57-d739c74d14ed)

**Comment by terrychenzw** [comment]
是个bug。当前标签页显示的方式，当关键词分支视图处于笔记下时，修改笔记后视图刷新异常。

临时的解决方案：
1. 关闭视图重新打开
2. 用左右分屏展示关键词分支视图和笔记
3. 用堆叠的方式展示关键词分支视图和笔记

长期方案：这个问题我还没有找到具体原因和解决的方法，需要更多研究。

**Comment by cygroup** [comment]
好的，就先用临时解决方案解决，还有一个建议，是否“关键词文件”的目录，可以支持当前所选的目录以及其下子目录都有效，这样在关键词的主目录下，就可以再用子目录做一些分组了，不会所有的关键词文件都集中在主目录下，很凌乱。




不吃鱼的猫
***@***.***

公众号：一只猫的文字圈


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "terrychenzw/obsidian-zettelkasten-navigation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 中午1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [terrychenzw/obsidian-zettelkasten-navigation] 笔记修改后，再回到关键词分支视图，会失效 (Issue #20)





 
是个bug。当前标签页显示的方式，当关键词分支视图处于笔记下时，修改笔记后视图刷新异常。
 
临时的解决方案：
  
关闭视图重新打开
 
用左右分屏展示关键词分支视图和笔记
 
用堆叠的方式展示关键词分支视图和笔记
  
长期方案：这个问题我还没有找到具体原因和解决的方法，需要更多研究。

**Comment by terrychenzw** [comment]
> 好的，就先用临时解决方案解决，还有一个建议，是否“关键词文件”的目录，可以支持当前所选的目录以及其下子目录都有效，这样在关键词的主目录下，就可以再用子目录做一些分组了，不会所有的关键词文件都集中在主目录下，很凌乱。


下个版本将支持子文件下的关键词

**Comment by terrychenzw** [comment]
[版本 0.0.45](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/releases/tag/0.0.45) 已解决。
