### ISSUE TITLE
关键词查询窗体显示不一致

### ISSUE THREAD

**Issue by cygroup** [terrychenzw/obsidian-zettelkasten-navigation#21]
我从0.0.36升级至0.0.44，发现在关键词查询窗体中，升级前已添加的关键词，所在笔记显示为编码，升级后新添加的关键词所在笔记显示为标题名称。
![008](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/96104161/400b1205-0f6e-4934-bcd8-d80b4734f4b9)

**Comment by cygroup** [comment]
我是用文件属性来设置编码的，和笔记标题是分开的

**Comment by terrychenzw** [comment]
提供一下你的主笔记frontmatter，和设置页的主笔记和关键词的设置。

初步判断是ID识别不到而不显示ID。

**Comment by cygroup** [comment]
后面进一步发现，再次打开关键词分支视图，就又都统一显示id了，应该是新建关键词那一下子时，没法正确获取到id，显示标题了。
![008](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/96104161/9d55ee6f-ccf7-4d6b-a1f1-165e13d24d4a)
![009](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/96104161/c85d5c44-a90d-406f-94cb-ed228c91ec67)
![011](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/96104161/ea150a1f-f288-4499-9ef1-8e4254373d37)

**Comment by cygroup** [comment]
能加个微信吗？沟通起来跟方便，这个github实在卡。。。
微信号：i-am-wright
