### ISSUE TITLE
建议：增加当前笔记子节点、兄弟节点最后编码提示

### ISSUE THREAD

**Issue by atseis** [terrychenzw/obsidian-zettelkasten-navigation#23]
在当前卡片基础上建立新卡片主要是2种行为：建立子节点、建立兄弟节点。
如当前有卡片  1, 1a, 1b, 1c, 1d, 1-1, 1-2, 1-3, 1-4, 1.1, 1.2, 1.a, 1.b, 1.c, 1.d, 1.e
那么当前笔记为 1 时，能够获知当前子节点不同方式最后编码提示为： 1d, 1-4, 1.2, 1.e
当前笔记为 1a 时，能够获知当前兄弟节点不同方式最后编码提示为： 1d, 1-4, 1.2, 1.e

**Comment by terrychenzw** [comment]
下个版本将增加右键菜单，可自定义命令，[功能效果](https://www.bilibili.com/video/BV1pzxjerENq/?spm_id_from=333.1365.list.card_archive.click)
