### ISSUE TITLE
建议预览节点笔记时可以显式笔记名

### ISSUE THREAD

**Issue by zhixiangCai** [terrychenzw/obsidian-zettelkasten-navigation#24]
建议预览节点笔记时可以显式笔记名，我使用“Folgezettel ID+空格+笔记名”，当前预览节点只显示Folgezettel ID，而笔记名通常是整个笔记内容的总结，对于快速获取笔记信息很重要。

**Comment by terrychenzw** [comment]
1. 设置里的【ID字段选项】选择“选项3”，并指定空格为分隔符
2. 关键词分支页面的【显示文本】下拉框里，选择“标题”和“ID+标题”，都可以显示笔记名
