### ISSUE TITLE
Failed to open view RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [terrychenzw/obsidian-zettelkasten-navigation#5]
> 经测试，如果MainNote文件夹有以下笔记，则会报错，无法渲染zk-index-graph，似乎和标题名有关？

## 文档标题

`9.1 50岁男性，间歇性跛行2个月，为什么查腰椎CT，不查颈椎CT或下肢肌电图？`

## 文档内容

```
---
Created: 2024-04-24
Tags: 
---

年龄因素（退行性变）+症状，考虑腰椎管狭窄症，腰椎管狭窄症诊断常用的检查包括腰椎X线、CT、MRI以及椎管造影。

```

**Comment by terrychenzw** [comment]
0.0.26 版本只支持文件名为ID。下个版本将增加文件名是：ID+标题的组合。

下个版本预计在插件成功上架OB三方插件市场后发布，敬请期待（上架审批进度：https://github.com/obsidianmd/obsidian-releases/pull/3393）

详情可以查看：https://github.com/terrychenzw/obsidian-zettelkasten-navigation/issues/4

**Comment by terrychenzw** [comment]
合并到https://github.com/terrychenzw/obsidian-zettelkasten-navigation/issues/4
