### ISSUE TITLE
[FR] 更多样式设置

### ISSUE THREAD

**Issue by wwjCMP** [terrychenzw/obsidian-zettelkasten-navigation#6]
![Snipaste_2024-04-30_21-45-01](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/32979859/661963f8-9c69-4460-89b4-7b84d8ef9a70)
这里的字体比其他文件中的字体要小，而且在dark模式下可读性也不太好

**Comment by wwjCMP** [comment]
dark模式下改一下色块的背景颜色

**Comment by terrychenzw** [comment]
背景色调整可以到style.css文件找 “.zk-index-mermaid”. 将里面的backgroup-color删除或者改为其它颜色就行。

字体大小下个版本会调整到12px。着急使用可以到main.js文件查找 ‘10px’，改为 ‘12px’.

**Comment by terrychenzw** [comment]
背景色调整可以到style.css文件找 “.zk-index-mermaid”. 将里面的backgroup-color删除或者改为其它颜色就行。

字体大小下个版本会调整到12px。着急使用可以到main.js文件查找 ‘10px’，改为 ‘12px’.

**Comment by wwjCMP** [comment]
![Snipaste_2024-05-07_00-40-58](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/32979859/8dc795e1-7699-407e-81ba-b15446b4c7b5)
显示在页面的中间区域，而不是顶端

**Comment by wwjCMP** [comment]
还有整个视窗扩大到整个页面是否更合理一点

**Comment by terrychenzw** [comment]
[0.0.33](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/releases/tag/0.0.33) 版本对 svg 的显示做了一些优化

**Comment by wwjCMP** [comment]
> 背景色调整可以到style.css文件找 “.zk-index-mermaid”. 将里面的background-color删除或者改为其它颜色就行。
> 
> 字体大小下个版本会调整到12px。着急使用可以到main.js文件查找 ‘10px’，改为 ‘12px’.

能单独改变dark模式下的背景色吗
