### ISSUE TITLE
[FR] 入链出链增加过滤

### ISSUE THREAD

**Issue by wwjCMP** [terrychenzw/obsidian-zettelkasten-navigation#7]
比如排除图片

**Comment by terrychenzw** [comment]
后续可以考虑增加 markdown only 的开关。出链只显示是markdown文件的。

**Comment by terrychenzw** [comment]
[版本 0.0.44](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/releases/tag/0.0.44) 已现实。
