### ISSUE TITLE
结合mehrmaid

### ISSUE THREAD

**Issue by wwjCMP** [terrychenzw/obsidian-zettelkasten-navigation#9]
https://github.com/huterguier/obsidian-mehrmaid
这是 Mermaid 增强插件，结合它是否有可能实现更丰富的显示

**Comment by terrychenzw** [comment]
mehrmaid这个插件我之前有留意过，感觉它更偏向白板，对标Canvas。而zettelkasten navigation对标的是图谱。所以我暂时不打算在zettelkasten navigation上做太复杂的显示。

比较可行的是，增加一键导出到Canvas，将当前显示的节点以卡片形成导出到一个新Canvas文件当中。合理使用Obsidian已有生态。不过导出到Canvas的卡片位置布局，当前还有一些逻辑问题没有解决。

**Comment by terrychenzw** [comment]
mehrmaid这个插件我之前有留意过，感觉它更偏向白板，对标Canvas。而zettelkasten navigation对标的是图谱。所以我暂时不打算在zettelkasten navigation上做太复杂的显示。

比较可行的是，增加一键导出到Canvas，将当前显示的节点以卡片形成导出到一个新Canvas文件当中。合理使用Obsidian已有生态。不过导出到Canvas的卡片位置布局，当前还有一些逻辑问题没有解决。

**Comment by terrychenzw** [comment]
> 不过导出到Canvas的卡片位置布局，当前还有一些逻辑问题没有解决。

下个版本将增加图标命令：导出到Canvas
